# Generated by Django 5.1.2 on 2024-10-19 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloggerprofilemodel',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='bloggerprofilemodel',
            name='Profile_Pic',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='Contact_No',
        ),
        migrations.RemoveField(
            model_name='viewersprofilemodel',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='viewersprofilemodel',
            name='Profile_Pic',
        ),
        migrations.AddField(
            model_name='bloggerprofilemodel',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bloggerprofilemodel',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='viewersprofilemodel',
            name='interests',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='viewersprofilemodel',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='viewersprofilemodel',
            name='preferred_content_type',
            field=models.CharField(blank=True, choices=[('articles', 'Articles'), ('videos', 'Videos'), ('podcasts', 'Both')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bloggerprofilemodel',
            name='Bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloggerprofilemodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bloggersProfile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('authority', 'Authority')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='viewersprofilemodel',
            name='Bio',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
