# Generated by Django 5.1.2 on 2024-10-20 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_bloggerprofilemodel_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostmodel',
            name='BlogBody',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='user_type',
            field=models.CharField(choices=[('viewers', 'Viewers'), ('blogger', 'Blogger')], max_length=100, null=True),
        ),
    ]
